# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bviolet/word2vec/cmkdep/pg_extension

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bviolet/word2vec/cmkdep/pg_extension

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bviolet/word2vec/cmkdep/pg_extension/CMakeFiles /home/bviolet/word2vec/cmkdep/pg_extension//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bviolet/word2vec/cmkdep/pg_extension/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_verbose

# Build rule for target.
test_verbose: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_verbose
.PHONY : test_verbose

# fast build rule for target.
test_verbose/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_verbose.dir/build.make CMakeFiles/test_verbose.dir/build
.PHONY : test_verbose/fast

#=============================================================================
# Target rules for targets named testsearch

# Build rule for target.
testsearch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testsearch
.PHONY : testsearch

# fast build rule for target.
testsearch/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsearch.dir/build.make CMakeFiles/testsearch.dir/build
.PHONY : testsearch/fast

src/testsearch/testsearch.o: src/testsearch/testsearch.cpp.o
.PHONY : src/testsearch/testsearch.o

# target to build an object file
src/testsearch/testsearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsearch.dir/build.make CMakeFiles/testsearch.dir/src/testsearch/testsearch.cpp.o
.PHONY : src/testsearch/testsearch.cpp.o

src/testsearch/testsearch.i: src/testsearch/testsearch.cpp.i
.PHONY : src/testsearch/testsearch.i

# target to preprocess a source file
src/testsearch/testsearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsearch.dir/build.make CMakeFiles/testsearch.dir/src/testsearch/testsearch.cpp.i
.PHONY : src/testsearch/testsearch.cpp.i

src/testsearch/testsearch.s: src/testsearch/testsearch.cpp.s
.PHONY : src/testsearch/testsearch.s

# target to generate assembly for a file
src/testsearch/testsearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsearch.dir/build.make CMakeFiles/testsearch.dir/src/testsearch/testsearch.cpp.s
.PHONY : src/testsearch/testsearch.cpp.s

src/tokenizer/tokenizer.o: src/tokenizer/tokenizer.cpp.o
.PHONY : src/tokenizer/tokenizer.o

# target to build an object file
src/tokenizer/tokenizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsearch.dir/build.make CMakeFiles/testsearch.dir/src/tokenizer/tokenizer.cpp.o
.PHONY : src/tokenizer/tokenizer.cpp.o

src/tokenizer/tokenizer.i: src/tokenizer/tokenizer.cpp.i
.PHONY : src/tokenizer/tokenizer.i

# target to preprocess a source file
src/tokenizer/tokenizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsearch.dir/build.make CMakeFiles/testsearch.dir/src/tokenizer/tokenizer.cpp.i
.PHONY : src/tokenizer/tokenizer.cpp.i

src/tokenizer/tokenizer.s: src/tokenizer/tokenizer.cpp.s
.PHONY : src/tokenizer/tokenizer.s

# target to generate assembly for a file
src/tokenizer/tokenizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsearch.dir/build.make CMakeFiles/testsearch.dir/src/tokenizer/tokenizer.cpp.s
.PHONY : src/tokenizer/tokenizer.cpp.s

src/tokenizer/unilib/unicode.o: src/tokenizer/unilib/unicode.cpp.o
.PHONY : src/tokenizer/unilib/unicode.o

# target to build an object file
src/tokenizer/unilib/unicode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsearch.dir/build.make CMakeFiles/testsearch.dir/src/tokenizer/unilib/unicode.cpp.o
.PHONY : src/tokenizer/unilib/unicode.cpp.o

src/tokenizer/unilib/unicode.i: src/tokenizer/unilib/unicode.cpp.i
.PHONY : src/tokenizer/unilib/unicode.i

# target to preprocess a source file
src/tokenizer/unilib/unicode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsearch.dir/build.make CMakeFiles/testsearch.dir/src/tokenizer/unilib/unicode.cpp.i
.PHONY : src/tokenizer/unilib/unicode.cpp.i

src/tokenizer/unilib/unicode.s: src/tokenizer/unilib/unicode.cpp.s
.PHONY : src/tokenizer/unilib/unicode.s

# target to generate assembly for a file
src/tokenizer/unilib/unicode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsearch.dir/build.make CMakeFiles/testsearch.dir/src/tokenizer/unilib/unicode.cpp.s
.PHONY : src/tokenizer/unilib/unicode.cpp.s

src/tokenizer/unilib/uninorms.o: src/tokenizer/unilib/uninorms.cpp.o
.PHONY : src/tokenizer/unilib/uninorms.o

# target to build an object file
src/tokenizer/unilib/uninorms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsearch.dir/build.make CMakeFiles/testsearch.dir/src/tokenizer/unilib/uninorms.cpp.o
.PHONY : src/tokenizer/unilib/uninorms.cpp.o

src/tokenizer/unilib/uninorms.i: src/tokenizer/unilib/uninorms.cpp.i
.PHONY : src/tokenizer/unilib/uninorms.i

# target to preprocess a source file
src/tokenizer/unilib/uninorms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsearch.dir/build.make CMakeFiles/testsearch.dir/src/tokenizer/unilib/uninorms.cpp.i
.PHONY : src/tokenizer/unilib/uninorms.cpp.i

src/tokenizer/unilib/uninorms.s: src/tokenizer/unilib/uninorms.cpp.s
.PHONY : src/tokenizer/unilib/uninorms.s

# target to generate assembly for a file
src/tokenizer/unilib/uninorms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testsearch.dir/build.make CMakeFiles/testsearch.dir/src/tokenizer/unilib/uninorms.cpp.s
.PHONY : src/tokenizer/unilib/uninorms.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_verbose"
	@echo "... testsearch"
	@echo "... src/testsearch/testsearch.o"
	@echo "... src/testsearch/testsearch.i"
	@echo "... src/testsearch/testsearch.s"
	@echo "... src/tokenizer/tokenizer.o"
	@echo "... src/tokenizer/tokenizer.i"
	@echo "... src/tokenizer/tokenizer.s"
	@echo "... src/tokenizer/unilib/unicode.o"
	@echo "... src/tokenizer/unilib/unicode.i"
	@echo "... src/tokenizer/unilib/unicode.s"
	@echo "... src/tokenizer/unilib/uninorms.o"
	@echo "... src/tokenizer/unilib/uninorms.i"
	@echo "... src/tokenizer/unilib/uninorms.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

